filter:
  paths:
    - "src/"
  excluded_paths:
    - "tests/"
  dependency_paths:
    - "vendor/"

checks:
  php: true

build:
  dependencies:
    before:
      - restore-from-cache repository "dependencies"
      - restore-from-cache repository "phpunit"
      - sudo mv /usr/bin/composer.phar /usr/bin/composer && sudo chmod +x /usr/bin/composer

    override:
      - composer install --no-scripts --prefer-dist --optimize-autoloader --no-interaction
      - command: wget https://get.symfony.com/cli/installer -O - | bash
        only_if: '[ "$SCRUTINIZER_BRANCH" == "master" ] && [ -z "$SCRUTINIZER_PR_SOURCE_BRANCH" ]'

    after:
      - store-in-cache repository "dependencies" vendor/

  nodes:
    tests:
      tests:
        override:
          - composer validate
          - ./vendor/bin/php-cs-fixer fix --dry-run -v
          - command: '~/.symfony/bin/symfony security:check --force-update'
            only_if: '[ "$SCRUTINIZER_BRANCH" == "master" ] && [ -z "$SCRUTINIZER_PR_SOURCE_BRANCH" ]'
          - command: ./vendor/bin/simple-phpunit --coverage-clover=code-coverage
            coverage:
              file: code-coverage
              format: clover
          - php-scrutinizer-run

        after:
          - store-in-cache repository "phpunit" vendor/bin/.phpunit/

  environment:
    php:
      version: 7.3
      pecl_extensions:
        - pcov
        - zip

build_failure_conditions:
  - 'elements.rating(<= D).new.exists' # No new classes/methods with a rating of D or worse.
  - 'project.metric("scrutinizer.quality", < 6)' # Code Quality Rating drops below 6
  - 'project.metric("scrutinizer.test_coverage", < 0.20)' # Code Coverage drops below 20%
