services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Superbrave\LoggerBundle\Adapter\SentryAdapter: ~

    Superbrave\LoggerBundle\Logger\Logger:
        arguments:
            $adapter: '@Superbrave\LoggerBundle\Adapter\SentryAdapter'
