services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Superbrave\LoggerBundle\Logger\Logger:
        arguments:
            $adapter: 'Superbrave\LoggerBundle\Adapter\SentryAdapter'
